bootstrap.servers=localhost:443
#kafka.topic=prod.consum.clients-test
kafka.topic=prod-consum-test
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="Test" password="Test_Pass";

group.id=clients
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
auto.offset.reset=earliest


# Use/Modify the below configs if using the certs for authentication

# Enable SSL
#security.protocol=SSL
 
# Path to the Truststore
#ssl.truststore.location=/path/to/client.truststore.jks
#ssl.truststore.password=your_truststore_password
 
# Path to the Keystore (if client authentication is required)
#ssl.keystore.location=/path/to/client.keystore.jks
#ssl.keystore.password=your_keystore_password
#ssl.key.password=your_key_password
 
# (Optional) SSL protocol and cipher settings
#ssl.endpoint.identification.algorithm=https
#ssl.protocol=TLSv1.2