spring.application.name=producer-application
server.port=8081

# Kafka PRODUCER Configuration
spring.kafka.bootstrap-servers=localhost:443
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Custom Topic
app.kafka.topic=prod.consum.clients-test


#security
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="Test" password="Test_Pass";


